<?php namespace Model\Perawi;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Daftar extends ORM {
	public $primary_key = 'Kode_Rawi';
	function _init()
	{
		self::$fields = array(
			'Kode_Rawi' => ORM::field('int[8]'),
			'Nama' => ORM::field('char[80]'),
			'Quality' => ORM::field('int[6]'),
			'Kalangan' => ORM::field('char[50]'),
			'Nasab' => ORM::field('char[40]'),
			'Kuniyah' => ORM::field('char[40]'),
			'Laqob' => ORM::field('char[40]'),
			'Negeri_Hidup' => ORM::field('char[30]'),
			'Negeri_Wafat' => ORM::field('char[30]'),
			'Tahun_Wafat' => ORM::field('char[8]'),
			'bukhari' => ORM::field('int[4]'),
			'muslim' => ORM::field('int[4]'),
			'abudaud' => ORM::field('int[4]'),
			'tirmidzi' => ORM::field('int[4]'),
			'nasai' => ORM::field('int[4]'),
			'ibnumajah' => ORM::field('int[4]'),
			'ahmad' => ORM::field('int[4]'),
			'malik' => ORM::field('int[4]'),
			'darimi' => ORM::field('int[4]'),
		);

	}
}