<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_had_imam extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'imamId' => array(
				'type' => 'INT',
				'constraint' => 10,
			),
			'namaTabel' => array(
				'type' => 'VARCHAR',
				'constraint' => 255,
			),
			'longNama' => array(
				'type' => 'VARCHAR',
				'constraint' => 255,
			),
			'imamSorting' => array(
				'type' => 'INT',
				'constraint' => 10,
			),
		));

		$this->dbforge->add_key('imamId', TRUE);

		$this->dbforge->create_table('had_imam', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('had_imam');
	}
}