<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_ind_list extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'ID_Indeks' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'Judul_Indeks' => array(
				'type' => 'VARCHAR',
				'constraint' => 255,
			),
		));

		$this->dbforge->create_table('ind_list', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('ind_list');
	}
}