<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_perawi_daftar extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'Kode_Rawi' => array(
				'type' => 'INT',
				'constraint' => 8,
			),
			'Nama' => array(
				'type' => 'VARCHAR',
				'constraint' => 80,
			),
			'Quality' => array(
				'type' => 'INT',
				'constraint' => 6,
			),
			'Kalangan' => array(
				'type' => 'VARCHAR',
				'constraint' => 50,
			),
			'Nasab' => array(
				'type' => 'VARCHAR',
				'constraint' => 40,
			),
			'Kuniyah' => array(
				'type' => 'VARCHAR',
				'constraint' => 40,
			),
			'Laqob' => array(
				'type' => 'VARCHAR',
				'constraint' => 40,
			),
			'Negeri_Hidup' => array(
				'type' => 'VARCHAR',
				'constraint' => 30,
			),
			'Negeri_Wafat' => array(
				'type' => 'VARCHAR',
				'constraint' => 30,
			),
			'Tahun_Wafat' => array(
				'type' => 'VARCHAR',
				'constraint' => 8,
			),
			'bukhari' => array(
				'type' => 'INT',
				'constraint' => 4,
			),
			'muslim' => array(
				'type' => 'INT',
				'constraint' => 4,
			),
			'abudaud' => array(
				'type' => 'INT',
				'constraint' => 4,
			),
			'tirmidzi' => array(
				'type' => 'INT',
				'constraint' => 4,
			),
			'nasai' => array(
				'type' => 'INT',
				'constraint' => 4,
			),
			'ibnumajah' => array(
				'type' => 'INT',
				'constraint' => 4,
			),
			'ahmad' => array(
				'type' => 'INT',
				'constraint' => 4,
			),
			'malik' => array(
				'type' => 'INT',
				'constraint' => 4,
			),
			'darimi' => array(
				'type' => 'INT',
				'constraint' => 4,
			),
		));

		$this->dbforge->create_table('perawi_daftar', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('perawi_daftar');
	}
}