<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_perawi_muslim extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'NoUrut' => array(
				'type' => 'INT',
				'constraint' => 6,
			),
			'NoHdt' => array(
				'type' => 'INT',
				'constraint' => 6,
			),
			'Kode_Rawi' => array(
				'type' => 'INT',
				'constraint' => 6,
			),
		));

		$this->dbforge->create_table('perawi_muslim', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('perawi_muslim');
	}
}