<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_smsuser extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 4,
			),
			'nm' => array(
				'type' => 'VARCHAR',
				'constraint' => 25,
			),
			'addr' => array(
				'type' => 'TEXT',
				'constraint' => 0,
			),
			'email' => array(
				'type' => 'VARCHAR',
				'constraint' => 35,
			),
			'username' => array(
				'type' => 'VARCHAR',
				'constraint' => 20,
			),
			'password' => array(
				'type' => 'VARCHAR',
				'constraint' => 200,
			),
			'stat' => array(
				'type' => 'INT',
				'constraint' => 1,
			),
			'type' => array(
				'type' => 'VARCHAR',
				'constraint' => 20,
			),
			'nohp' => array(
				'type' => 'VARCHAR',
				'constraint' => 20,
			),
			'key' => array(
				'type' => 'VARCHAR',
				'constraint' => 255,
			),
		));

		$this->dbforge->add_key('id', TRUE);

		$this->dbforge->create_table('smsuser', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('smsuser');
	}
}