<?php namespace Model\Biografi;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Imam extends ORM {
	
	public $primary_key = 'bioId';

	function _init()
	{
		self::$fields = array(
			'bioId' => ORM::field('auto[10]'),
			'bioImam' => ORM::field('char[255]'),
			'bioImamFull' => ORM::field('char[255]'),
			'bioContent' => ORM::field('string'),
		);

	}
}