<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Footnote extends ORM {
	
	function _init()
	{
		self::$fields = array(
			'NoHdt' => ORM::field('int[6]'),
			'Isi' => ORM::field('string'),
		);

	}
}