<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Smsuser extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
		self::$fields = array(
			'id' => ORM::field('auto[4]'),
			'nm' => ORM::field('char[25]'),
			'addr' => ORM::field('string'),
			'email' => ORM::field('char[35]'),
			'username' => ORM::field('char[20]'),
			'password' => ORM::field('char[200]'),
			'stat' => ORM::field('int[1]'),
			'type' => ORM::field('char[20]'),
			'nohp' => ORM::field('char[20]'),
			'key' => ORM::field('char[255]'),
		);

	}
}