<?php namespace Model\Kumpulan;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Marfu extends ORM {
	
	function _init()
	{
		self::$fields = array(
			'NoUrut' => ORM::field('int[8]'),
			'Sumber' => ORM::field('char[20]'),
			'NoHdt' => ORM::field('int[8]'),
		);

	}
}